# Generated by Django 5.2.8 on 2025-11-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomoBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', '食費'), ('Entertainment', '娯楽費'), ('Work', '経費')], max_length=100)),
                ('price', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
