# Generated by Django 5.2.8 on 2025-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homobudget',
            name='category',
            field=models.CharField(choices=[('Food', '食費'), ('book', '本'), ('Favorite', '趣味'), ('subscribe', 'サブスク'), ('Entertainment', '娯楽費'), ('Work', '経費')], max_length=100),
        ),
    ]
