# Generated by Django 5.2.8 on 2025-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0002_alter_homobudget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homobudget',
            name='content',
            field=models.CharField(default='', max_length=100),
        ),
    ]
