# Generated by Django 5.2.8 on 2025-11-16 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0003_homobudget_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homobudget',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 17, 57, 8, 741820, tzinfo=datetime.timezone.utc), verbose_name='日付'),
        ),
    ]
