# Generated by Django 5.2.8 on 2025-11-16 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0004_alter_homobudget_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homobudget',
            name='created_date',
        ),
        migrations.AddField(
            model_name='homobudget',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 17, 59, 58, 960865, tzinfo=datetime.timezone.utc), verbose_name='日付'),
        ),
    ]
