# Generated by Django 5.2.8 on 2025-11-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0005_remove_homobudget_created_date_homobudget_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homobudget',
            name='created_at',
            field=models.DateField(),
        ),
    ]
