# Generated by Django 5.2.8 on 2025-11-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0007_alter_homobudget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homobudget',
            name='category',
            field=models.CharField(choices=[('Food', '食費'), ('book', '書籍'), ('Favorite', '趣味'), ('subscribe', 'サブスク'), ('Entertainment', '娯楽費'), ('Work', '経費'), ('income', '収入')], max_length=100),
        ),
    ]
