# Generated by Django 5.2.8 on 2025-11-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebudget', '0008_alter_homobudget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homobudget',
            name='category',
            field=models.CharField(choices=[('Food', '食費'), ('book', '書籍'), ('Favorite', '趣味'), ('subscribe', 'サブスク'), ('Entertainment', '娯楽費'), ('Work', '経費'), ('income', '収入'), ('other', 'その他')], max_length=100),
        ),
    ]
